sweepo_site:
    resource: "@SweepoSiteBundle/Controller/"
    type:     annotation
    prefix:   /

sweepo_stream:
    resource: "@SweepoStreamBundle/Controller/"
    type:     annotation
    prefix:   /

sweepo_user:
    resource: "@SweepoUserBundle/Controller/"
    type:     annotation
    prefix:   /

sweepo_core:
    resource: "@SweepoCoreBundle/Controller/"
    type:     annotation
    prefix:   /